// 配置select列表,将会生成对应的过滤器name + Filter

/**
 * 配置项1
 */
export const deviceType = [
  { value: '1', label: '条件1' },
  { value: '2', label: '条件2' },
  { value: '3', label: '条件3' },
  { value: '4', label: '条件4' },
  { value: '5', label: '条件5' },
  { value: '6', label: '条件6' },
  { value: '7', label: '条件7' },
  { value: '8', label: '条件8' },
  { value: '9', label: '条件9' },
  { value: '10', label: '条件10' },
]

/**
 * 配置项2
 */
export const deviceModel = [
  { value: '1', label: '条件1' },
  { value: '2', label: '条件2' },
  { value: '3', label: '条件3' },
  { value: '4', label: '条件4' },
  { value: '5', label: '条件5' },
]

/* --------------用户管理 ----------------- */
// 性别
export const userSex = [
  { value: '0', label: '全部' },
  { value: '1', label: '男' },
  { value: '2', label: '女' },
]

// 地区
export const userProvince = [
  { value: '0', label: '全部' },
  { value: "110000", label: "北京市" },
  { value: "120000", label: "天津市" },
  { value: "130000", label: "河北省" },
  { value: "140000", label: "山西省" },
  { value: "150000", label: "内蒙古自治区" },
  { value: "210000", label: "辽宁省" },
  { value: "220000", label: "吉林省" },
  { value: "230000", label: "黑龙江省" },
  { value: "310000", label: "上海市" },
  { value: "320000", label: "江苏省" },
  { value: "330000", label: "浙江省" },
  { value: "340000", label: "安徽省" },
  { value: "350000", label: "福建省" },
  { value: "360000", label: "江西省" },
  { value: "370000", label: "山东省" },
  { value: "410000", label: "河南省" },
  { value: "420000", label: "湖北省" },
  { value: "430000", label: "湖南省" },
  { value: "440000", label: "广东省" },
  { value: "450000", label: "广西壮族自治区" },
  { value: "460000", label: "海南省" },
  { value: "500000", label: "重庆市" },
  { value: "510000", label: "四川省" },
  { value: "520000", label: "贵州省" },
  { value: "530000", label: "云南省" },
  { value: "540000", label: "西藏自治区" },
  { value: "610000", label: "陕西省" },
  { value: "620000", label: "甘肃省" },
  { value: "630000", label: "青海省" },
  { value: "640000", label: "宁夏回族自治区" },
  { value: "650000", label: "新疆维吾尔自治区" },
  { value: "710000", label: "台湾省" },
  { value: "810000", label: "香港特别行政区" },
  { value: "820000", label: "澳门特别行政区" },
]

// 参加任务
export const userTask = [
  { value: '0', label: '全部' },
  { value: '1', label: '是' },
  { value: '2', label: '否' },
]

// 购买商品
export const userShop = [
  { value: '0', label: '全部' },
  { value: '1', label: '是' },
  { value: '2', label: '否' },
]

/* --------------权限管理 ----------------- */
// [状态]
export const authorityStatus = [
  { value: '0', label: '全部' },
  { value: '1', label: '启用' },
  { value: '2', label: '禁用' },
]

/* --------------任务管理 ----------------- */
// [年份]
export const taskYear = [
  { value: '5', label: '5' },
  { value: '6', label: '6' },
  { value: '7', label: '7' },
  { value: '8', label: '8' },
  { value: '9', label: '9' },
  { value: '10', label: '10' },
  { value: '11', label: '11' },
  { value: '12', label: '12' },
  { value: '13', label: '13' },
  { value: '14', label: '14' },
  { value: '15', label: '15' },
  { value: '16', label: '16' },
  { value: '17', label: '17' },
  { value: '18', label: '18' },
  { value: '19', label: '19' },
  { value: '20', label: '20' },
  { value: '21', label: '21' },
  { value: '22', label: '22' },
  { value: '23', label: '23' },
  { value: '24', label: '24' },
  { value: '25', label: '25' },
  { value: '26', label: '26' },
  { value: '27', label: '27' },
  { value: '28', label: '28' },
  { value: '29', label: '29' },
  { value: '30', label: '30' },
  { value: '31', label: '31' },
  { value: '32', label: '32' },
  { value: '33', label: '33' },
  { value: '34', label: '34' },
  { value: '35', label: '35' },
  { value: '36', label: '36' },
  { value: '37', label: '37' },
  { value: '38', label: '38' },
  { value: '39', label: '39' },
  { value: '40', label: '40' },
  { value: '41', label: '41' },
  { value: '42', label: '42' },
  { value: '43', label: '43' },
  { value: '44', label: '44' },
  { value: '45', label: '45' },
  { value: '46', label: '46' },
  { value: '47', label: '47' },
  { value: '48', label: '48' },
  { value: '49', label: '49' },
  { value: '50', label: '50' },
  { value: '51', label: '51' },
  { value: '52', label: '52' },
  { value: '53', label: '53' },
  { value: '54', label: '54' },
  { value: '55', label: '55' },
  { value: '56', label: '56' },
  { value: '57', label: '57' },
  { value: '58', label: '58' },
  { value: '59', label: '59' },
  { value: '60', label: '60' },
  { value: '61', label: '61' },
  { value: '62', label: '62' },
  { value: '63', label: '63' },
  { value: '64', label: '64' },
  { value: '65', label: '65' },
  { value: '66', label: '66' },
  { value: '67', label: '67' },
  { value: '68', label: '68' },
  { value: '69', label: '69' },
  { value: '70', label: '70' },
  { value: '71', label: '71' },
  { value: '72', label: '72' },
  { value: '73', label: '73' },
  { value: '74', label: '74' },
  { value: '75', label: '75' },
  { value: '76', label: '76' },
  { value: '77', label: '77' },
  { value: '78', label: '78' },
  { value: '79', label: '79' },
  { value: '80', label: '80' },
]

/* --------------优惠券管理 ----------------- */
// [类型]
export const couponType = [
    { value: '0', label: '全部' },
    { value: '1', label: '全品类优惠券' },
    { value: '2', label: '特定品类优惠券' },
  ]
  // [领取方式]
export const couponWay = [
    { value: '0', label: '全部' },
    { value: '1', label: '公开领取' },
    { value: '2', label: '奖品领取' },
  ]
  /* --- Modal --- */
  // [类型]
export const couponTypeModal = [
    { value: '1', label: '全品类优惠券' },
    { value: '2', label: '特定品类优惠券' },
  ]
  // [领取方式]
export const couponWayModal = [
    { value: '1', label: '公开领取' },
    { value: '2', label: '奖品领取' },
  ]
  // [适用平台]
export const couponWayPlatform = [
  { value: '1', label: 'HIZERO商城' },
  { value: '2', label: 'HIZERO后台' },
]

/* --------------财务管理 ----------------- */
// [类型]
export const financeType = [
  { value: '0', label: '全部' },
  { value: '1', label: '支付宝' },
  { value: '2', label: '微信' },
]

/* --------------商城管理 ----------------- */
// [状态]
export const orderStatus = [
  { value: '0', label: '全部' },
  { value: '3', label: '待收货' },
  { value: '4', label: '交易成功' },
  { value: '5', label: '用户取消' },
]

/* --------------消息推送 ----------------- */
// [地区]
export const userProvinceModal = [
  { value: '0', label: '全部' },
  { value: "110000", label: "北京市" },
  { value: "120000", label: "天津市" },
  { value: "130000", label: "河北省" },
  { value: "140000", label: "山西省" },
  { value: "150000", label: "内蒙古自治区" },
  { value: "210000", label: "辽宁省" },
  { value: "220000", label: "吉林省" },
  { value: "230000", label: "黑龙江省" },
  { value: "310000", label: "上海市" },
  { value: "320000", label: "江苏省" },
  { value: "330000", label: "浙江省" },
  { value: "340000", label: "安徽省" },
  { value: "350000", label: "福建省" },
  { value: "360000", label: "江西省" },
  { value: "370000", label: "山东省" },
  { value: "410000", label: "河南省" },
  { value: "420000", label: "湖北省" },
  { value: "430000", label: "湖南省" },
  { value: "440000", label: "广东省" },
  { value: "450000", label: "广西壮族自治区" },
  { value: "460000", label: "海南省" },
  { value: "500000", label: "重庆市" },
  { value: "510000", label: "四川省" },
  { value: "520000", label: "贵州省" },
  { value: "530000", label: "云南省" },
  { value: "540000", label: "西藏自治区" },
  { value: "610000", label: "陕西省" },
  { value: "620000", label: "甘肃省" },
  { value: "630000", label: "青海省" },
  { value: "640000", label: "宁夏回族自治区" },
  { value: "650000", label: "新疆维吾尔自治区" },
  { value: "710000", label: "台湾省" },
  { value: "810000", label: "香港特别行政区" },
  { value: "820000", label: "澳门特别行政区" },
]


// [国家数据]
export const countryModel = [
  { value: 'Angola', label: '安哥拉' },
  { value: 'Afghanistan', label: '阿富汗' },
  { value: 'Albania', label: '阿尔巴尼亚' },
  { value: 'Algeria', label: '阿尔及利亚' },
  { value: 'Andorra', label: '安道尔共和国' },
  { value: 'Anguilla', label: '安圭拉岛' },
  { value: 'Antigua and Barbuda', label: '安提瓜和巴布达' },
  { value: 'Argentina', label: '阿根廷' },
  { value: 'Armenia', label: '亚美尼亚' },
  { value: 'Ascension', label: '阿森松' },
  { value: 'Australia', label: '澳大利亚' },
  { value: 'Austria', label: '奥地利' },
  { value: 'Azerbaijan', label: '阿塞拜疆' },
  { value: 'Bahamas', label: '巴哈马' },
  { value: 'Bahrain', label: '巴林' },
  { value: 'Bangladesh', label: '孟加拉国' },
  { value: 'Barbados', label: '巴巴多斯' },
  { value: 'Belarus', label: '白俄罗斯' },
  { value: 'Belgium', label: '比利时' },
  { value: 'Belize', label: '伯利兹' },
  { value: 'Benin', label: '贝宁' },
  { value: 'Bermuda Is', label: '百慕大群岛' },
  { value: 'Bolivia', label: '玻利维亚' },
  { value: 'Botswana', label: '博茨瓦纳' },
  { value: 'Brazil', label: '巴西' },
  { value: 'Brunei', label: '文莱' },
  { value: 'Bulgaria', label: '保加利亚' },
  { value: 'Burkina Faso', label: '布基纳法索' },
  { value: 'Burma', label: '缅甸' },
  { value: 'Burundi', label: '布隆迪' },
  { value: 'Cameroon', label: '喀麦隆' },
  { value: 'Canada', label: '加拿大' },
  { value: 'Cayman Is', label: '开曼群岛' },
  { value: 'Central African Republic', label: '中非共和国' },
  { value: 'Chad', label: '乍得' },
  { value: 'Chile', label: '智利' },
  { value: 'China', label: '中国' },
  { value: 'Colombia', label: '哥伦比亚' },
  { value: 'Congo', label: '刚果' },
  { value: 'Cook Is', label: '库克群岛' },
  { value: 'Costa Rica', label: '哥斯达黎加' },
  { value: 'Cuba', label: '古巴' },
  { value: 'Cyprus', label: '塞浦路斯' },
  { value: 'Czech Republic', label: '捷克' },
  { value: 'Denmark', label: '丹麦' },
  { value: 'Djibouti', label: '吉布提' },
  { value: 'Dominica Rep', label: '多米尼加共和国' },
  { value: 'Ecuador', label: '厄瓜多尔' },
  { value: 'Egypt', label: '埃及' },
  { value: 'EI Salvador', label: '萨尔瓦多' },
  { value: 'Estonia', label: '爱沙尼亚' },
  { value: 'Ethiopia', label: '埃塞俄比亚' },
  { value: 'Fiji', label: '斐济' },
  { value: 'Finland', label: '芬兰' },
  { value: 'France', label: '法国' },
  { value: 'French Guiana', label: '法属圭亚那' },
  { value: 'French Polynesia', label: '法属玻利尼西亚' },
  { value: 'Gabon', label: '加蓬' },
  { value: 'Gambia', label: '冈比亚' },
  { value: 'Georgia', label: '格鲁吉亚' },
  { value: 'Germany', label: '德国' },
  { value: 'Ghana', label: '加纳' },
  { value: 'Gibraltar', label: '直布罗陀' },
  { value: 'Greece', label: '希腊' },
  { value: 'Grenada', label: '格林纳达' },
  { value: 'Guam', label: '关岛' },
  { value: 'Guatemala', label: '危地马拉' },
  { value: 'Guinea', label: '几内亚' },
  { value: 'Guyana', label: '圭亚那' },
  { value: 'Haiti', label: '海地' },
  { value: 'Honduras', label: '洪都拉斯' },
  { value: 'Hungary', label: '匈牙利' },
  { value: 'Iceland', label: '冰岛' },
  { value: 'India', label: '印度' },
  { value: 'Indonesia', label: '印度尼西亚' },
  { value: 'Iran', label: '伊朗' },
  { value: 'Iraq', label: '伊拉克' },
  { value: 'Ireland', label: '爱尔兰' },
  { value: 'Israel', label: '以色列' },
  { value: 'Italy', label: '意大利' },
  { value: 'Ivory Coast', label: '科特迪瓦' },
  { value: 'Jamaica', label: '牙买加' },
  { value: 'Japan', label: '日本' },
  { value: 'Jordan', label: '约旦' },
  { value: 'Kampuchea (Cambodia )', label: '柬埔寨' },
  { value: 'Kazakstan', label: '哈萨克斯坦' },
  { value: 'Kenya', label: '肯尼亚' },
  { value: 'Korea', label: '韩国' },
  { value: 'Kuwait', label: '科威特' },
  { value: 'Kyrgyzstan', label: '吉尔吉斯坦' },
  { value: 'Laos', label: '老挝' },
  { value: 'Latvia', label: '拉脱维亚' },
  { value: 'Lebanon', label: '黎巴嫩' },
  { value: 'Lesotho', label: '莱索托' },
  { value: 'Liberia', label: '利比里亚' },
  { value: 'Libya', label: '利比亚' },
  { value: 'Liechtenstein', label: '列支敦士登' },
  { value: 'Lithuania', label: '立陶宛' },
  { value: 'Luxembourg', label: '卢森堡' },
  { value: 'Madagascar', label: '马达加斯加' },
  { value: 'Malawi', label: '马拉维' },
  { value: 'Malaysia', label: '马来西亚' },
  { value: 'Maldives', label: '马尔代夫' },
  { value: 'Mali', label: '马里' },
  { value: 'Malta', label: '马耳他' },
  { value: 'Mariana Is', label: '马里亚那群岛' },
  { value: 'Martinique', label: '马提尼克' },
  { value: 'Mauritius', label: '毛里求斯' },
  { value: 'Mexico', label: '墨西哥' },
  { value: 'Moldova', label: '摩尔多瓦' },
  { value: 'Monaco', label: '摩纳哥' },
  { value: 'Mongolia', label: '蒙古' },
  { value: 'Montserrat Is', label: '蒙特塞拉特岛' },
  { value: 'Morocco', label: '摩洛哥' },
  { value: 'Mozambique', label: '莫桑比克' },
  { value: 'Namibia', label: '纳米比亚' },
  { value: 'Nauru', label: '瑙鲁' },
  { value: 'Nepal', label: '尼泊尔' },
  { value: 'Netheriands Antilles', label: '荷属安的列斯' },
  { value: 'Netherlands', label: '荷兰' },
  { value: 'New Zealand', label: '新西兰' },
  { value: 'Nicaragua', label: '尼加拉瓜' },
  { value: 'Niger', label: '尼日尔' },
  { value: 'Nigeria', label: '尼日利亚' },
  { value: 'North Korea', label: '朝鲜' },
  { value: 'Norway', label: '挪威' },
  { value: 'Oman', label: '阿曼' },
  { value: 'Pakistan', label: '巴基斯坦' },
  { value: 'Panama', label: '巴拿马' },
  { value: 'Papua New Cuinea', label: '巴布亚新几内亚' },
  { value: 'Paraguay', label: '巴拉圭' },
  { value: 'Peru', label: '秘鲁' },
  { value: 'Philippines', label: '菲律宾' },
  { value: 'Poland', label: '波兰' },
  { value: 'Portugal', label: '葡萄牙' },
  { value: 'Puerto Rico', label: '波多黎各' },
  { value: 'Qatar', label: '卡塔尔' },
  { value: 'Reunion', label: '留尼旺' },
  { value: 'Romania', label: '罗马尼亚' },
  { value: 'Russia', label: '俄罗斯' },
  { value: 'Saint Lueia', label: '圣卢西亚' },
  { value: 'Saint Vincent', label: '圣文森特岛' },
  { value: 'Samoa Eastern', label: '东萨摩亚(美)' },
  { value: 'Samoa Western', label: '西萨摩亚' },
  { value: 'San Marino', label: '圣马力诺' },
  { value: 'Sao Tome and Principe', label: '圣多美和普林西比' },
  { value: 'Saudi Arabia', label: '沙特阿拉伯' },
  { value: 'Senegal', label: '塞内加尔' },
  { value: 'Seychelles', label: '塞舌尔' },
  { value: 'Sierra Leone', label: '塞拉利昂' },
  { value: 'Singapore', label: '新加坡' },
  { value: 'Slovakia', label: '斯洛伐克' },
  { value: 'Slovenia', label: '斯洛文尼亚' },
  { value: 'Solomon Is', label: '所罗门群岛' },
  { value: 'Somali', label: '索马里' },
  { value: 'South Africa', label: '南非' },
  { value: 'Spain', label: '西班牙' },
  { value: 'SriLanka', label: '斯里兰卡' },
  { value: 'St.Lucia', label: '圣卢西亚' },
  { value: 'St.Vincent', label: '圣文森特' },
  { value: 'Sudan', label: '苏丹' },
  { value: 'Suriname', label: '苏里南' },
  { value: 'Swaziland', label: '斯威士兰' },
  { value: 'Sweden', label: '瑞典' },
  { value: 'Switzerland', label: '瑞士' },
  { value: 'Syria', label: '叙利亚' },
  { value: 'Tajikstan', label: '塔吉克斯坦' },
  { value: 'Tanzania', label: '坦桑尼亚' },
  { value: 'Thailand', label: '泰国' },
  { value: 'Togo', label: '多哥' },
  { value: 'Tonga', label: '汤加' },
  { value: 'Trinidad and Tobago', label: '特立尼达和多巴哥' },
  { value: 'Tunisia', label: '突尼斯' },
  { value: 'Turkey', label: '土耳其' },
  { value: 'Turkmenistan', label: '土库曼斯坦' },
  { value: 'Uganda', label: '乌干达' },
  { value: 'Ukraine', label: '乌克兰' },
  { value: 'United Arab Emirates', label: '阿拉伯联合酋长国' },
  { value: 'United Kiongdom', label: '英国' },
  { value: 'United States of America', label: '美国' },
  { value: 'Uruguay', label: '乌拉圭' },
  { value: 'Uzbekistan', label: '乌兹别克斯坦' },
  { value: 'Venezuela', label: '委内瑞拉' },
  { value: 'Vietnam', label: '越南' },
  { value: 'Yemen', label: '也门' },
  { value: 'Yugoslavia', label: '南斯拉夫' },
  { value: 'Zimbabwe', label: '津巴布韦' },
  { value: 'Zaire', label: '扎伊尔' },
  { value: 'Zambia', label: '赞比亚' }

]
